# load_dotenv must run before any other import that reads os.getenv at module level
from dotenv import load_dotenv

load_dotenv()

import asyncio
import datetime
import json
import os
import sys
import uuid

from loguru import logger

from agents.analysis import AnalysisAgent, AnalysisAgentManual
from agents.user import UserAgent
from db.log import LogDB
from tools.common import save_analysis
from utils.agent_runner import Agent as AgentRunner
from utils.prompt_utils import extract_json_blocks

MAX_ANALYSIS_RETRIES = int(os.getenv("MAX_ANALYSIS_RETRIES", 3))
MAX_CONV_RETRIES = int(os.getenv("MAX_CONV_RETRIES", 3))
DEFAULT_MODEL = os.getenv("MODEL_NAME", "gemini-2.5-flash")

# Timeout per individual LLM call (seconds). Prevents a single hung API call
# from blocking the loop forever.
ITERATION_TIMEOUT = int(os.getenv("ITERATION_TIMEOUT", 120))

# Maximum total wall-clock time for one full run (conversation + analysis).
# When exceeded, the current iteration is skipped and analysis runs immediately.
RUN_TIMEOUT = int(os.getenv("RUN_TIMEOUT", 600))

# Timeout per individual analysis attempt (seconds).
ANALYSIS_TIMEOUT = int(os.getenv("ANALYSIS_TIMEOUT", 120))

MAX_CHAT_ITERATIONS = int(os.getenv("MAX_CHAT_ITERATIONS", 20))

# Max agents running concurrently within a single process.
# Prevents Gemini API rate-limit errors when batch_size is large.
MAX_CONCURRENT_AGENTS = int(os.getenv("MAX_CONCURRENT_AGENTS", 3))

DEFAULT_ACCOUNT_ID = os.getenv("DEFAULT_ACCOUNT_ID", "1")


# ── Helpers ───────────────────────────────────────────────────────────────────


def fmt_duration(seconds: float) -> str:
    """Format seconds into human-readable duration string."""
    if seconds < 1:
        return f"{seconds * 1000:.0f}ms"
    elif seconds < 60:
        return f"{seconds:.1f}s"
    elif seconds < 3600:
        minutes = int(seconds // 60)
        secs = seconds % 60
        return f"{minutes}m {secs:.1f}s"
    else:
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        secs = seconds % 60
        return f"{hours}h {minutes}m {secs:.0f}s"


# ── Analysis agent ─────────────────────────────────────────────────────────────


async def run_analysis_agent(agent, run_id: str, user_id: str, context: str):
    log_db = LogDB()
    for attempt in range(1, MAX_ANALYSIS_RETRIES + 2):
        try:
            runner = AgentRunner(user_id=user_id, agent=agent)
            await runner.generate()
            # Use run_id as fallback session_id when no messages were saved to DB.
            # The AnalysisAgent prompt handles the empty-messages case gracefully.
            session_id = log_db.get_session_id_by_run_id(run_id) or run_id
            await asyncio.wait_for(
                runner.from_text(session_id), timeout=ANALYSIS_TIMEOUT
            )
            if not log_db.insight_exists_by_run_id(run_id):
                raise RuntimeError("AnalysisAgent did not save any insights.")
            logger.info(f"AnalysisAgent completed successfully for run_id {run_id}.")
            return
        except asyncio.TimeoutError:
            logger.error(
                f"AnalysisAgent attempt {attempt} timed out after {ANALYSIS_TIMEOUT}s."
            )
        except Exception as e:
            logger.error(f"AnalysisAgent attempt {attempt} failed: {e}")
        if attempt <= MAX_ANALYSIS_RETRIES:
            logger.info(
                f"Retrying AnalysisAgent. Attempts left: {MAX_ANALYSIS_RETRIES - attempt + 1}"
            )

    logger.error(
        "Max retries reached for AnalysisAgent. Falling back to manual analysis."
    )
    await run_analysis_agent_manual(run_id, context, user_id, agent.model)


async def run_analysis_agent_manual(
    run_id: str, context: str, user_id: str, model: str
):
    try:
        logger.info(
            f"Running AnalysisAgent manual fallback for user_id={user_id}, model={model}"
        )
        log_db = LogDB()
        analysis_agent = AnalysisAgentManual(
            context=context, user_id=user_id, model=model
        )
        runner = AgentRunner(user_id=user_id, agent=analysis_agent.Build())
        await runner.generate()
        messages = log_db.get_by_run_id(run_id)
        res = await runner.from_text(json.dumps(messages))
        logger.debug(f"Manual AnalysisAgent response: {res}")
        session_id = log_db.get_session_id_by_run_id(run_id) or run_id
        if not res:
            logger.warning(
                f"Manual AnalysisAgent returned empty result for run_id {run_id}."
            )
            res = "No insights generated by manual AnalysisAgent."
        save_analysis(session_id=session_id, analysis=res, run_id=run_id)
        logger.info(f"Manual AnalysisAgent completed for run_id {run_id}.")
    except Exception as e:
        logger.error(f"Error in manual AnalysisAgent fallback: {e}")
        logger.error("Manual AnalysisAgent failed. No further retries.")


# ── Core agent run ─────────────────────────────────────────────────────────────
def generate_run_id():
    return str(uuid.uuid4())


async def _conversation_attempt(
    context: str,
    user_id: str,
    model: str,
    run_id: str,
    item_label: str,
    attempt: int,
    account_id: str = DEFAULT_ACCOUNT_ID,
) -> tuple[bool, object]:
    """
    Run one full conversation attempt.
    Returns (got_messages: bool, analysis_agent_built).
    got_messages=True means at least one send_to_agent call succeeded.
    """
    log_db = LogDB()

    analysis_agent_obj = AnalysisAgent(context=context, user_id=user_id, model=model)
    analysis_agent_obj.set_run_id(run_id)
    analysis_agent_built = analysis_agent_obj.Build()

    user_agent = UserAgent(
        context=context,
        user_id=user_id,
        model=model,
        sub_agents=[analysis_agent_built],
    )
    user_agent.set_run_id(run_id)
    agent = user_agent.Build()

    runner = AgentRunner(user_id=user_id, agent=agent)
    await runner.generate()

    previous_response = None
    iteration_count = 0
    max_iterations = int(MAX_CHAT_ITERATIONS)
    exits_run_case = log_db.exits_case_for_run_id(run_id)
    if not exits_run_case:
        context_obj = context if isinstance(context, dict) else json.loads(context)
        log_db.add_case(run_id=run_id, payload=context_obj)
    log_db.create_conversation(run_id=run_id, account_id=account_id, user_id=user_id)
    try:
        while True:
            iteration_count += 1
            iter_start = datetime.datetime.now()

            res = await runner.from_text(
                "start" if previous_response is None else previous_response
            )

            iter_elapsed = (datetime.datetime.now() - iter_start).total_seconds()
            logger.debug(
                f"{item_label} [A{attempt}] Iter {iteration_count} | {fmt_duration(iter_elapsed)}"
            )

            if res is None or res.strip() == "" or res.strip() == "{}":
                logger.error(
                    f"{item_label} [A{attempt}] No response at iteration {iteration_count}."
                )
                break

            res_json = extract_json_blocks(res)
            if (
                res_json.get("conversation_end", False)
                or res_json.get("insights")
                or "insights" in res
            ):
                logger.info(
                    f"{item_label} [A{attempt}] Conversation ended at iteration {iteration_count}."
                )
                break

            previous_response = res
            max_iterations -= 1
            if max_iterations <= 0:
                logger.info(
                    f"{item_label} [A{attempt}] Max iterations reached ({iteration_count})."
                )
                break

    except KeyboardInterrupt:
        raise
    except Exception as e:
        logger.error(
            f"{item_label} [A{attempt}] Error at iteration {iteration_count}: {e}"
        )

    got_messages = len(log_db.get_by_run_id(run_id)) > 0
    return got_messages, analysis_agent_built


async def run_agent(
    context: str,
    user_id: str,
    model: str,
    batch=None,
    item_index: int = None,
    total_items: int = None,
    account_id: str = DEFAULT_ACCOUNT_ID,
):
    item_label = (
        f"[Batch {batch} | Item {item_index + 1}/{total_items}]"
        if item_index is not None
        else "[Single]"
    )
    item_start = datetime.datetime.now()
    log_db = LogDB()

    logger.info(f"{item_label} Starting | user_id={user_id} | model={model}")

    final_run_id = None
    final_analysis_agent = None

    for attempt in range(1, MAX_CONV_RETRIES + 1):
        run_id = generate_run_id()
        final_run_id = run_id

        try:
            got_messages, analysis_agent = await _conversation_attempt(
                context=context,
                user_id=user_id,
                model=model,
                run_id=run_id,
                item_label=item_label,
                attempt=attempt,
                account_id=account_id,
            )
            final_analysis_agent = analysis_agent
        except KeyboardInterrupt:
            logger.info(f"{item_label} Interrupted.")
            break
        except Exception as e:
            logger.error(f"{item_label} [A{attempt}] Unexpected error: {e}")
            got_messages = False

        if got_messages:
            logger.info(
                f"{item_label} [A{attempt}] Conversation produced messages. OK."
            )
            break

        # No messages generated — decide whether to retry
        if attempt < MAX_CONV_RETRIES:
            backoff = 2**attempt  # 2s, 4s
            logger.warning(
                f"{item_label} [A{attempt}] No messages. "
                f"Retrying in {backoff}s... ({MAX_CONV_RETRIES - attempt} left)"
            )
            await asyncio.sleep(backoff)
        else:
            ctx_preview = str(context)[:300] if context else "N/A"
            logger.error(
                f"{item_label} All {MAX_CONV_RETRIES} attempts failed. "
                f"Saving failure record. Context preview: {ctx_preview}"
            )
            save_analysis(
                session_id=run_id,
                run_id=run_id,
                analysis=json.dumps(
                    {
                        "insights": (
                            f"Fallo tras {MAX_CONV_RETRIES} intentos: el agente no generó "
                            f"mensajes en ningún intento (final=True, has_content=False). "
                            f"Contexto: {ctx_preview}"
                        ),
                        "complete": False,
                    }
                ),
            )

    # ── Post-run: ensure analysis exists ─────────────────────────────────────
    if final_run_id:
        has_analysis = log_db.insight_exists_by_run_id(final_run_id)
        if not has_analysis:
            logger.warning(
                f"{item_label} No analysis for run_id {final_run_id}. Running AnalysisAgent fallback."
            )
            await run_analysis_agent(
                final_analysis_agent, final_run_id, user_id, context
            )

        if not log_db.insight_exists_by_run_id(final_run_id):
            fallback_sid = log_db.get_session_id_by_run_id(final_run_id) or final_run_id
            save_analysis(
                session_id=fallback_sid,
                run_id=final_run_id,
                analysis=json.dumps(
                    {
                        "insights": "No se pudo generar análisis tras todos los intentos.",
                        "complete": False,
                    }
                ),
            )
            logger.warning(
                f"{item_label} Emergency analysis saved for run_id {final_run_id}."
            )

    item_elapsed = (datetime.datetime.now() - item_start).total_seconds()
    logger.info(f"{item_label} DONE | Duration: {fmt_duration(item_elapsed)}")
    return final_run_id


# ── Batch run ─────────────────────────────────────────────────────────────────


async def run_from_json_file(
    file_path: str, batch_size: int = 10, max_iterations: int = 30
):
    try:
        with open(file_path, "r") as f:
            data = json.load(f)
    except Exception as e:
        logger.error(f"Failed to read JSON file: {e}")
        return

    if not isinstance(data, list):
        logger.error("JSON file must contain a list of conversation turns.")
        return

    total_items = len(data)
    total_batches = (total_items + batch_size - 1) // batch_size
    process_start = datetime.datetime.now()

    logger.info("=" * 60)
    logger.info("PROCESS START")
    logger.info(f"  Total items:   {total_items}")
    logger.info(f"  Batch size:    {batch_size}")
    logger.info(f"  Total batches: {total_batches}")
    logger.info(f"  Started at:    {process_start.isoformat()}")
    logger.info("=" * 60)

    batch_timings = []

    for i in range(0, total_items, batch_size):
        batch = data[i : i + batch_size]
        batch_num = i // batch_size + 1
        batch_start = datetime.datetime.now()

        logger.info("-" * 60)
        logger.info(
            f"BATCH {batch_num}/{total_batches} | "
            f"Items {i + 1}-{min(i + batch_size, total_items)} of {total_items} | "
            f"Size: {len(batch)}"
        )

        sem = asyncio.Semaphore(MAX_CONCURRENT_AGENTS)

        async def _run_with_sem(turn, idx):
            async with sem:
                return await run_agent(
                    context=turn,
                    user_id=turn.get("user_id", "default_user"),
                    model=turn.get("model", DEFAULT_MODEL),
                    batch=batch_num,
                    item_index=i + idx,
                    total_items=total_items,
                )

        tasks = [_run_with_sem(turn, idx) for idx, turn in enumerate(batch)]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        batch_elapsed = (datetime.datetime.now() - batch_start).total_seconds()
        batch_timings.append(batch_elapsed)

        failures = sum(1 for r in results if isinstance(r, Exception))
        successes = len(results) - failures

        process_elapsed = (datetime.datetime.now() - process_start).total_seconds()
        avg_per_batch = process_elapsed / batch_num
        remaining_batches = total_batches - batch_num
        eta_seconds = avg_per_batch * remaining_batches

        logger.info(
            f"BATCH {batch_num}/{total_batches} DONE | "
            f"Duration: {fmt_duration(batch_elapsed)} | "
            f"OK: {successes} | FAIL: {failures}"
        )
        if remaining_batches > 0:
            logger.info(
                f"  Progress: {batch_num}/{total_batches} batches | "
                f"Elapsed: {fmt_duration(process_elapsed)} | "
                f"ETA remaining: ~{fmt_duration(eta_seconds)}"
            )

        for idx, r in enumerate(results):
            if isinstance(r, Exception):
                logger.error(f"  Item {i + idx + 1} failed with error: {r}")

    process_elapsed = (datetime.datetime.now() - process_start).total_seconds()

    logger.info("=" * 60)
    logger.info("PROCESS COMPLETE")
    logger.info(f"  Total duration:     {fmt_duration(process_elapsed)}")
    logger.info(f"  Total items:        {total_items}")
    logger.info(
        f"  Avg per item:       {fmt_duration(process_elapsed / total_items) if total_items > 0 else 'N/A'}"
    )
    logger.info(f"  Total batches:      {total_batches}")
    if batch_timings:
        logger.info(f"  Fastest batch:      {fmt_duration(min(batch_timings))}")
        logger.info(f"  Slowest batch:      {fmt_duration(max(batch_timings))}")
        logger.info(
            f"  Avg batch duration: {fmt_duration(sum(batch_timings) / len(batch_timings))}"
        )
    logger.info(f"  Finished at:        {datetime.datetime.now().isoformat()}")
    logger.info("=" * 60)
