import os
import json
import asyncio
import concurrent.futures
from typing import Dict

import requests as r
from loguru import logger

from db.sql import LogDB

SERVICE_URL = os.getenv("AGENT_URL", "")
REQUEST_TIMEOUT = int(os.getenv("REQUEST_TIMEOUT", "120"))
_TOKEN = os.getenv("AGENT_TOKEN", "")

_http_executor = concurrent.futures.ThreadPoolExecutor(max_workers=20)


def clean_response(response_dict: dict) -> dict:
    if isinstance(response_dict, str):
        response_dict = json.loads(response_dict)

    clean = {**response_dict}
    if "traces" in clean:
        for trace in clean["traces"]:
            payload = trace.get("payload", {})
            content = payload.get("content", {})
            if isinstance(content, dict):
                for part in content.get("parts", []):
                    part.pop("thoughtSignature", None)
    return clean


def _http_post(data: dict) -> dict:
    """Blocking HTTP call, meant to run in a thread pool executor."""
    response = r.post(
        url=f"{SERVICE_URL}/chat",
        json=data,
        headers={"Authorization": f"Bearer {_TOKEN}"},
        timeout=REQUEST_TIMEOUT,
    )
    return response.json()


def send_to_agent(
    message: str,
    user_id: str = "default_user",
    is_hsm: bool = False,
    hsm_name: str = "",
    images: list = None,
    attachments: list = None,
    account_id: str = "3057",
    session_id: str = "",
    session_backend: str = "memory",
    persist_session: bool = False,
    run_id: str = "",
    scenario_group_id: str = "",
    scenario: str = "",
    *args,
    **kwargs,
) -> dict:
    """
    Send a message to the agent and get the response.
    Args:
        message (str): The message to send to the agent.
        user_id (str): The ID of the user sending the message.
        is_hsm (bool): Whether the message is an HSM (Highly Structured Message).
        hsm_name (str): The name of the HSM template, if applicable.
        images (list[str]): A list of image URLs to include in the message.
        attachments (list[dict[str, str]]): A list of attachment dicts to include.
        account_id (str): The ID of the account associated with the message.
        session_id (str): The ID of the session for maintaining context.
        session_backend (str): The backend to use for session management.
        persist_session (bool): Whether to persist the session after processing.
        scenario_group_id (str): The ID of the scenario group.
        scenario (str): The name of the scenario being executed.
    Returns:
        dict: The response from the agent.
    """
    images = images or []
    attachments = attachments or []

    data = {
        "account_id": account_id,
        "user_id": user_id,
        "text": message,
        "is_hsm": is_hsm,
        "hsm_name": hsm_name,
        "images": images,
        "attachments": attachments,
        "session_id": session_id,
        "session_backend": session_backend,
        "persist_session": persist_session,
    }

    # Run the blocking HTTP call off the event loop so parallel agents in a
    # batch don't block each other while waiting for the external service.
    loop = asyncio.get_event_loop()
    if loop.is_running():
        future = _http_executor.submit(_http_post, data)
        response = future.result()
    else:
        response = _http_post(data)

    response = clean_response(response)
    save_interaction(
        message=message,
        answer=response,
        user_id=user_id,
        files=attachments,
        images=images,
        run_id=run_id,
        scenario_group_id=scenario_group_id,
        scenario=scenario,
    )
    return response


def save_interaction(
    message: str,
    answer: dict,
    user_id: str = "default_user",
    files: list = None,
    images: list = None,
    run_id: str = "",
    scenario_group_id: str = "",
    scenario: str = "",
):
    """
    Save the interaction between the user and the agent to the database.
    """
    try:
        log_db = LogDB()
        log_db.add(
            user_id=user_id,
            message=message,
            raw_response=json.dumps(answer),
            response=answer.get("text", ""),
            session_id=answer.get("session_id", ""),
            files=files or [],
            images=images or [],
            run_id=run_id,
            scenario_group_id=scenario_group_id,
            scenario=scenario,
        )
    except Exception as e:
        logger.error(f"Error saving interaction: {e}")


def save_analysis(
    analysis: str, session_id: str, run_id: str, *args, **kwargs
) -> Dict[str, str]:
    """
    Save the analysis generated by the AnalysisAgent to the database.
    Args:
        analysis (str): The analysis data to be saved.
        session_id (str): The ID of the session associated with the analysis.
        run_id (str): The run ID to associate with the analysis.
    Returns:
        dict: A dictionary indicating the status of the save operation.
    """
    logger.info(f"Saving analysis, session_id: {session_id}, analysis: {analysis}")

    analysis_dict = {}
    if isinstance(analysis, str):
        try:
            analysis_dict = json.loads(analysis)
        except json.JSONDecodeError:
            analysis_dict = {"insights": analysis}
    elif isinstance(analysis, dict):
        analysis_dict = analysis
    else:
        logger.error("Invalid analysis format. Must be a JSON string or a dictionary.")
        return {
            "status": "error",
            "message": "Invalid analysis format. Must be a JSON string or a dictionary.",
        }

    # Normalize `complete` regardless of whether the LLM returned a bool or a string
    complete_val = analysis_dict.get("complete", False)
    if isinstance(complete_val, bool):
        complete = complete_val
    else:
        complete = str(complete_val).lower() == "true"

    try:
        log_db = LogDB()
        log_db.add_insight(
            session_id=session_id,
            run_id=run_id,
            analysis=analysis_dict.get("insights", ""),
            complete=complete,
        )
        logger.info("Analysis saved successfully.")
        return {"status": "success", "message": "Analysis saved successfully."}
    except Exception as e:
        logger.error(f"Error saving analysis: {e}")
        return {"status": "error", "message": f"Error saving analysis: {e}"}
