from ast import Dict

from dotenv import load_dotenv
import requests as r
import os
from loguru import logger
import json
from db.sql import LogDB
from typing import Dict

load_dotenv()

SERVICE_URL = os.getenv("AGENT_URL", "")


def _generate_token() -> str:
    return os.getenv("AGENT_TOKEN", "")


def clean_response(response_dict: dict):
    if isinstance(response_dict, str):
        response_dict = json.loads(response_dict)

    clean = {**response_dict}
    if "traces" in clean:
        for trace in clean["traces"]:
            payload = trace.get("payload", {})
            content = payload.get("content", {})
            if isinstance(content, dict):
                for part in content.get("parts", []):
                    part.pop("thoughtSignature", None)
    return clean


def send_to_agent(
    message: str,
    user_id: str = "default_user",
    is_hsm: bool = False,
    hsm_name: str = "",
    images: list[str] = [],
    attachments: list[dict[str, str]] = [],
    account_id: str = "3057",
    session_id: str = "",
    session_backend: str = "memory",
    persist_session: bool = False,
) -> dict:
    """
    Send a message to the agent and get the response.
    Args:
        message (str): The message to send to the agent.
        user_id (str): The ID of the user sending the message.
        is_hsm (bool): Whether the message is an HSM (Highly Structured Message).
        hsm_name (str): The name of the HSM template, if applicable.
        images (list[str]): A list of image URLs to include in the message. e.g ( ["https://example.com/image1.jpg", "https://example.com/image2.jpg"])
        attachments (list[dict[str, str]]): A list of attachment URLs to include in the message. e.g ( [{ "url": "https://example.com/solicitud_ingreso.pdf", "type": "pdf" }])
        account_id (str): The ID of the account associated with the message.
        session_id (str): The ID of the session for maintaining context.
        session_backend (str): The backend to use for session management (e.g., "memory", "redis").
        persist_session (bool): Whether to persist the session after the message is processed.
    Returns:
        dict: The response from the agent.
    """
    data = {
        "account_id": account_id,
        "user_id": user_id,
        "text": message,
        "is_hsm": is_hsm,
        "hsm_name": hsm_name,
        "images": images,
        "attachments": attachments,
        "session_id": session_id,
        "session_backend": session_backend,
        "persist_session": persist_session,
    }
    logger.info(f"Sending message to agent, data: {data}")
    response = r.post(
        url=f"{SERVICE_URL}/chat",
        json=data,
        headers={
            "Authorization": f"Bearer {_generate_token()}",
        },
    )
    response = response.json()
    response = clean_response(response)
    logger.info(f"Received response from agent: {response}")
    save_interaction(
        message=message,
        answer=response,
        user_id=user_id,
        files=attachments,
        images=images,
    )
    return response


def save_interaction(
    message: str,
    answer: dict,
    user_id: str = "default_user",
    files: list[dict] = [],
    images: list[str] = [],
):
    """
    Save the interaction between the user and the agent to the database.
    Args:
        message (str): The message sent by the user.
        answer (dict): The response received from the agent full dictionary.
        user_id (str): The ID of the user involved in the interaction.
    Returns:
        None
    """
    logger.info(
        f"Saving interaction, message: {message}, answer: {answer}, user_id: {user_id}"
    )
    try:
        log_db = LogDB()
        log_db.add(
            user_id=user_id,
            message=message,
            raw_response=json.dumps(answer),
            response=answer.get("text", ""),
            session_id=answer.get("session_id", ""),
            files=files,
            images=images,
        )
    except Exception as e:
        logger.error(f"Error saving interaction: {e}")


def save_analysis(analysis: str, session_id: str, *args, **kwargs) -> Dict[str, str]:
    """
    Save the analysis generated by the AnalysisAgent to the database.
    Args:
        analysis (str): The analysis data to be saved.
        session_id (str): The ID of the session associated with the analysis.
    Returns:
        dict: A dictionary indicating the status of the save operation.
    """
    logger.info(f"Saving analysis, session_id: {session_id}, analysis: {analysis}")
    analysis_dict = {}
    if isinstance(analysis, str):
        try:
            analysis_dict = json.loads(analysis)
        except json.JSONDecodeError as e:
            analysis_dict = {
                "insights": analysis,
            }
    elif isinstance(analysis, dict):
        analysis_dict = analysis
    else:
        logger.error("Invalid analysis format. Must be a JSON string or a dictionary.")
        return {
            "status": "error",
            "message": "Invalid analysis format. Must be a JSON string or a dictionary.",
        }
    try:
        log_db = LogDB()
        log_db.add_insight(
            session_id=session_id,
            analysis=analysis_dict.get("insights", ""),
        )
        return {"status": "success", "message": "Analysis saved successfully."}
    except Exception as e:
        logger.error(f"Error saving analysis: {e}")
        return {"status": "error", "message": f"Error saving analysis: {e}"}
